---
name: Update local data archive

on:
  # Manual button in Github.
  workflow_dispatch:
  # Run on a schedule
  schedule:
    - cron: '*/5 * * * *'
    - cron: '*/35 * * * *'

jobs:
  scheduled:
    runs-on: ubuntu-latest
    steps:
      - name: Check out this repo
        # https://github.com/actions/checkout
        uses: actions/checkout@v3

      - name: Install Python
        # https://github.com/actions/setup-python
        # Will install python version from .python-version
        uses: actions/setup-python@v4
        with:
          python-version: '3.10.6'
          cache: pip

      - name: Install Python packages
        run: |-
          make install

      - name: Fetch latest data and save as CSV
        run: |-
          # Download data
          # Regional forward 48h
          python run.py download --output_directory data --now | tee commit_msg.txt
          # Regional past 24h
          python run.py download --output_directory data --now --endpoint regional_pt24h | tee -a commit_msg.txt
          # National
          python run.py download --output_directory data --now --endpoint national_fw48h | tee -a commit_msg.txt
          python run.py download --output_directory data --now --endpoint national_pt24h | tee -a commit_msg.txt
          python run.py download --output_directory data --now --endpoint national_generation_pt24h | tee -a commit_msg.txt
          # Wrangle data to CSV
          python run.py wrangle --input_directory data/regional_fw48h --delete_json | tee -a commit_msg.txt
          python run.py wrangle --input_directory data/regional_pt24h --delete_json | tee -a commit_msg.txt
          python3 run.py wrangle --input_directory "data/national_generation_pt24h" --endpoint "national_generation_pt24h" --delete_json | tee -a commit_msg.txt

      - name: Commit and push new data
        run: |-
          git config user.name "Automated"
          git config user.email "actions@users.noreply.github.com"
          git add data\*/*.csv data\*/*.json
          git commit --file commit_msg.txt || exit 0
          git pull
          git push
