---
name: Update local data archive

on:
  # Manual button in Github.
  workflow_dispatch:
  # Run on a schedule
  schedule:
    - cron: '*/5 * * * *'
    - cron: '*/35 * * * *'

jobs:
  scheduled:
    runs-on: ubuntu-latest
    steps:
      - name: Check out this repo
        # https://github.com/actions/checkout
        uses: actions/checkout@v3

      - name: Install Python
        # https://github.com/actions/setup-python
        # Will install python version from .python-version
        uses: actions/setup-python@v4
        with:
          python-version: '3.10.6'
          cache: pip

      - name: Install Python packages
        run: |-
          make install

      - name: Fetch latest data
        run: |-
          # Download data
          # Regional forward, from now
          python run.py download --output_directory data_forecasts --now | tee commit_msg.txt
          # (temporary) Regional past, from now
          python run.py download --output_directory data_past --now --endpoint regional_past | tee -a commit_msg.txt
          # (temporary) National fixed timepoint to track variation in forecast and actual before/after
          python run.py download --output_directory data_national_fixed --start_date "2023-03-13T12:01Z" -n 1 --endpoint national --unique_names | tee -a commit_msg.txt

      - name: Commit and push if it changed
        run: |-
          git config user.name "Automated"
          git config user.email "actions@users.noreply.github.com"
          git add data\*/*.json
          git commit --file commit_msg.txt || exit 0
          git pull
          git push
