---
name: Update local data archive

on:
  # Manual button in Github.
  workflow_dispatch:
  # Run on a schedule
  schedule:
    # 5 and 35 past the hour except at 1:35AM
    - cron: '5 * * * *'
    - cron: '35 0,2-23 * * *'

jobs:
  scheduled:
    runs-on: ubuntu-latest
    steps:
      - name: Check out this repo
        # https://github.com/actions/checkout
        uses: actions/checkout@v3

      - name: Install Python
        # https://github.com/actions/setup-python
        # Will install python version from .python-version
        uses: actions/setup-python@v4
        with:
          python-version: '3.10.6'
          cache: pip

      - name: Install Python packages
        run: |-
          make install

      - name: Fetch latest data and save as JSON
        run: |-
          # Download data
          # Regional forward 48h
          python run.py download --output_directory data --now | tee commit_msg.txt
          # Regional past 24h
          python run.py download --output_directory data --now --endpoint regional_pt24h | tee -a commit_msg.txt
          # National
          python run.py download --output_directory data --now --endpoint national_fw48h | tee -a commit_msg.txt
          python run.py download --output_directory data --now --endpoint national_pt24h | tee -a commit_msg.txt
          python run.py download --output_directory data --now --endpoint national_generation_pt24h | tee -a commit_msg.txt

      - name: Commit and push new data
        run: |-
          git config user.name "Automated"
          git config user.email "actions@users.noreply.github.com"
          git add data\*/*.csv data\*/*.json
          git commit --file commit_msg.txt || exit 0
          git pull
          git push
